language: go
sudo: false
services:
- docker
env:
  global:
  - DOCKER_REPO=itsdalmo/ssm-sh
  - PROJECT_NAME=ssm-sh
matrix:
  include:
  - os: osx
    go: 1.11.x
    env:
    - TARGET=darwin
    - ARCH=amd64
  - os: linux
    go: 1.11.x
    env:
    - TARGET=linux
    - ARCH=amd64
  - os: linux
    go: 1.11.x
    env:
    - TARGET=windows
    - ARCH=amd64
    - EXT=.exe
notifications:
  email: false
script:
- make build-release
deploy:
  provider: releases
  api_key:
    secure: VmFjxvxzQPBgXb9u9XdMxocTvnSWFTW+/HhzOGeVABSaHumNxr1TfqxxxjOh8sHDQqLy65q0msny9JTgBC6FcTcW+GQaMfesirHOUvoMi2ZKJKEN/M6ODtHCV/DenvoSXpzVQO5YcWAOVSfRbB6Uu2CkB5hImrynI/lkn1kbI4uLVHSBDeTkZmTD4dmVtmSWtzUx4Rhryrbfj4fFuPOI98Xy2bsxBlLdtn5cudZbBCafY/62bSxQVqn9b7mUnHc/W5A9828MBJQOADwgS8oRkUEGuMCf4vwYx9ma4FRa3TIMWGjgRmp4QTCXP3XdXrCw/1advZBY5CWD8V84AdAzcFJHor+gJjcTr2IfOPqrdLdJXuMmHzzuxjr04ODfxcfV9fOiJZI0kYtIi+Cbtp/2nSTZlGCOsqsyc2zIZeZjW0fewRa89bu/6n+7w0ceAONeypAshAt2AHf45pV//zPxvJDMs4XV6Hi3ChjWmvmKO3gyd0xrEOaQ6ZLOtd8bVGyMcp4QH805rQvVgyaghTi7Fz61OpIDtXxoEBqhhLJ1SiQBHIL2UGoxKNHc0o9/I/gQT/IQB3oR/EDAV74zhIFzXXvGYJTNZfrqbQg9zyk51uicYTi85QMLrkQJ5dB9i1od1peLrRVPFZN0Xua2jhcG0Jk9BW7RaWec+IlaveuZyRY=
  file: "${PROJECT_NAME}-${TARGET}-amd64${EXT}"
  skip_cleanup: true
  on:
    repo: itsdalmo/ssm-sh
    tags: true
